# Site settings
title: "刘先燚"
description: "个人简介"
host: 0.0.0.0
port: 4000


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "liuxinyi"
resume_name-cn:                 "刘先燚"
resume_title:                   "Personal profile"
resume_title-cn:                "简介"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "goog@tju.edu.cn"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "17709886453"
resume_contact_address:         "Lab 330, Teaching Building 26, Tianjin University"

resume_header_contact_info:     "Lab 330, Teaching Building 26, Tianjin University • 17709886453 • goog@tju.edu.cn"
display_header_contact_info:    "false"

resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"
resume_header_intro-cn: "<p>团队合作能力强，具有探索精神，善于克服难题，寻找处理问题的最优方案。</p><p>在长期比赛与项目中，面对难题时能够保持积极的心态，有充足的耐心和毅力，有较强的动手能力和自学能力。</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_research:        true
resume_section_competition:     true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/liuxianyi"
  resume_gitee_url:            "https://gitee.com/liuxianyi"
  # resume_twitter_url:           "http://twitter.com/liuxianyi"
  # resume_dribbble_url:          "https://dribbble.com/liuxianyi"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
